// Code generated by protoc-gen-go.
// source: game.proto
// DO NOT EDIT!

/*
Package tesla is a generated protocol buffer package.

It is generated from these files:
	game.proto
	lobby.proto
	players.proto
	validation.proto

It has these top-level messages:
	EventGameStart
	EventGameEnd
*/
package tesla

import proto "github.com/golang/protobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

type EventGameStart struct {
	GameID           *uint64 `protobuf:"varint,1,req" json:"GameID,omitempty"`
	StartTime        *int64  `protobuf:"varint,2,req" json:"StartTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EventGameStart) Reset()         { *m = EventGameStart{} }
func (m *EventGameStart) String() string { return proto.CompactTextString(m) }
func (*EventGameStart) ProtoMessage()    {}

func (m *EventGameStart) GetGameID() uint64 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *EventGameStart) GetStartTime() int64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

type EventGameEnd struct {
	GameID           *uint64 `protobuf:"varint,1,req" json:"GameID,omitempty"`
	EndTime          *int64  `protobuf:"varint,2,req" json:"EndTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *EventGameEnd) Reset()         { *m = EventGameEnd{} }
func (m *EventGameEnd) String() string { return proto.CompactTextString(m) }
func (*EventGameEnd) ProtoMessage()    {}

func (m *EventGameEnd) GetGameID() uint64 {
	if m != nil && m.GameID != nil {
		return *m.GameID
	}
	return 0
}

func (m *EventGameEnd) GetEndTime() int64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

func init() {
}
