// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Tesla
{
	public partial class LobbyPlayerJoin
	{
		public ulong PlayerID { get; set; }

		public long EventTime { get; set; }

	}

	public partial class LobbyPlayerLeave
	{
		public ulong PlayerID { get; set; }

		public long EventTime { get; set; }

	}

	/// <summary> Lobby chat is handled by the dedicated server. A</summary>
	public partial class LobbyChatMessage
	{
		public enum MessageTarget
		{
			All = 1,
			Team = 2,
		}

		public ulong PlayerID { get; set; }

		public long EventTime { get; set; }

		public string Text { get; set; }

		public Tesla.LobbyChatMessage.MessageTarget Target { get; set; }

	}

}
