// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Tesla
{
	/// <summary>
	/// <para> PlayerJoinRequest is sent by the DS to the CS when a player wants to join the DS.</para>
	/// <para> The CS verifies the JoinHash sent by the PC to the DS and responds with a PlayerJoinResponse.</para>
	/// </summary>
	public partial class PlayerJoinRequest
	{
		public ulong RequestID { get; set; }

		public ulong PlayerID { get; set; }

		public byte[] AuthenticationHash { get; set; }

	}

	/// <summary> PlayerJoinResponse is sent from the CS to the DS. The field `Valid` indicates wether the JoinRequest was valid.</summary>
	public partial class PlayerJoinResponse
	{
		public ulong RequestID { get; set; }

		public bool Valid { get; set; }

	}

}
